version: '2.3'
services:

  numrp3:
    image: numrp3:a-3.8
    build: .
    stop_grace_period: 30s
    #devices:
    #  - /dev/video0:/dev/video0
    #  - /dev/snd:/dev/snd
    command: /bin/sh -c "ln -sf /dev/stdout /var/log/nginx/access.log && 
        ln -sf /dev/stderr /var/log/nginx/error.log &&
        /opt/init/init.sh && 
        exec /sbin/runsvdir -P /etc/service"
    environment:
      - TZ=${TZ:-Asia/Jakarta}
      - HOSTS_ACME=${HOSTS_ACME:-}
      - ALPINE_PASSWORD=${ALPINE_PASSWORD:-alpine}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-tiger}
      - POSTGRES_DB=${POSTGRES_DB:-$POSTGRES_USER}
      - MYSQL_ROOT_PWD=${MYSQL_ROOT_PWD:-mysql}
      - MYSQL_USER=${MYSQL_USER:-}
      - MYSQL_USER_PWD=${MYSQL_USER_PWD:-}
      - MYSQL_USER_DB=${MYSQL_USER_DB:-}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-}
      - HOSTNAME=${HOSTNAME}
      - HTTP_PORT=${HTTP_PORT:-}
      - HTTPS_PORT=${HTTPS_PORT:-}
    volumes:
      - ./data/cfg/mysql/:/etc/mysql/conf.d/
      - ./data/cfg/nginx/:/etc/nginx/conf.d/
      - ./data/cfg/ssh/:/etc/ssh/
      - ./data/cfg/uwsgi/:/etc/uwsgi/conf.d/
      - ./data/keys/:/var/keys/
      - ./data/ssl/:/etc/ssl/private/
      - ./data/web/apps/:/var/www/html/
      - ./data/web/pyenvs/:/var/envs/
      - mysql:/var/lib/mysql/
      - pgsql:/var/lib/postgresql/data/
      - redis:/var/lib/redis/
    ports:
      - "${ADDR_BIND:-0.0.0.0}:${SSH_PORT:-2222}:22"
      - "${ADDR_BIND:-0.0.0.0}:${HTTP_PORT:-80}:80"
      - "${ADDR_BIND:-0.0.0.0}:${HTTPS_PORT:-443}:443"
      - "${ADDR_BIND:-0.0.0.0}:${MYSQL_PORT:-3306}:3306"
      - "${ADDR_BIND:-0.0.0.0}:${PGSQL_PORT:-5432}:5432"
      - "${ADDR_BIND:-0.0.0.0}:5000:5000"
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    hostname: numrp3.local
    networks:
      backnet:
        aliases:
          - numrp3

networks:
  backnet:
    driver: bridge

volumes:
  mysql:
  pgsql:
  redis:
